[tox]
requires =
    tox>=4.22
envlist =
    py39
    py310
    py311
    py312
    py313
    py314
    py315
    pypy3

skip_missing_interpreters = true


[testenv]
dependency_groups = test
commands = pytest {posargs}
