package:
    name: toolz
    version: "0.7.4"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
    build:
      - setuptools
      - python

    run:
      - python

test:
    requires:
      - pytest
    imports:
      - toolz
    commands:
      - py.test -x --doctest-modules --pyargs toolz

about:
    home: http://toolz.readthedocs.org/
    license: BSD
