# Alternatively, consider using https://pre-commit.ci/
name: pre-commit checks

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  pre-commit:
    name: pre-commit-hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
        env:
          SKIP: "no-commit-to-branch"
