name: Pyright

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  type-check:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
